# Database Setup Instructions - Manual Setup
# If the automated scripts don't work, use MySQL Workbench directly

Write-Host "======================================"
Write-Host "Pharmac Database Manual Setup"
Write-Host "======================================"
Write-Host ""
Write-Host "Since the MySQL service encountered issues, please follow these manual steps:"
Write-Host ""
Write-Host "OPTION 1: Using MySQL Workbench (Recommended)"
Write-Host "=========================================="
Write-Host ""
Write-Host "1. Open MySQL Workbench (should be running)"
Write-Host ""
Write-Host "2. Click '+' to create a new connection:"
Write-Host "   - Connection Name: Pharmac Local"
Write-Host "   - Hostname: localhost"
Write-Host "   - Port: 3306"
Write-Host "   - Username: root"
Write-Host "   - Password: (the password from your MySQL installation)"
Write-Host ""
Write-Host "3. Click 'Test Connection' to verify"
Write-Host ""
Write-Host "4. Double-click the connection to open"
Write-Host ""
Write-Host "5. File > Open SQL Script"
Write-Host "   Select: C:\Users\ADITYA\Downloads\dream-weaver-main (1)\Pharmac\database\init-database.sql"
Write-Host ""
Write-Host "6. Click the lightning bolt icon (⚡) to execute"
Write-Host ""
Write-Host "7. Check the output panel - you should see:"
Write-Host "   - Database setup complete!"
Write-Host "   - Tables created"
Write-Host "   - agent_activities, queries, reports, results, users, visual_insights"
Write-Host ""
Write-Host ""
Write-Host "OPTION 2: Using MySQL Command Line"
Write-Host "=========================================="
Write-Host ""
Write-Host "If MySQL service cannot be fixed, reinstall it:"
Write-Host ""
Write-Host "1. Go to: https://dev.mysql.com/downloads/installer/"
Write-Host "2. Download and run: mysql-installer-community-8.0.*.msi"
Write-Host "3. In installer, select 'Remove' to uninstall current version"
Write-Host "4. Then select 'Add' and choose 'MySQL Server 8.0'"
Write-Host "5. Proceed with installation"
Write-Host "6. When prompted for configuration, choose 'Development Machine'"
Write-Host "7. Set root password (remember it!)"
Write-Host "8. Finish installation"
Write-Host ""
Write-Host "Then open PowerShell and run:"
Write-Host '$sql = Get-Content "c:\Users\ADITYA\Downloads\dream-weaver-main (1)\Pharmac\database\init-database.sql" -Raw'
Write-Host '$sql | &"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe" -u root -p'
Write-Host ""
Write-Host ""
Write-Host "OPTION 3: Create a Batch File for Initialization"
Write-Host "=========================================="
Write-Host ""
Write-Host "Create a file: C:\mysql-init.sql with the database setup code"
Write-Host "Then run MySQL with: mysql -u root -p < C:\mysql-init.sql"
Write-Host ""
Write-Host "======================================"
Write-Host "Database Setup File Ready"
Write-Host "======================================"
Write-Host ""
Write-Host "SQL file location:"
Write-Host "c:\Users\ADITYA\Downloads\dream-weaver-main (1)\Pharmac\database\init-database.sql"
Write-Host ""
Write-Host "Press Enter when database setup is complete..."
Read-Host
